name: Test
env:
  REPO_OWNER: rtuteja15o9
  REPO_NAME: example-event-dispatcher-workflows
  GITHUB_TOKEN: ${{ secrets.TOKEN }}
on:
  repository_dispatch:
    types: [run-test]
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: echo
        run: echo ${{github.event.client_payload}} && echo rahul
