name: Done
env:
  REPO_OWNER: rtuteja15o9
  REPO_NAME: example-event-dispatcher-workflows
  GITHUB_TOKEN: ${{ secrets.TOKEN }}
on:
  repository_dispatch:
    types: [run-test]
jobs:
  done:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Install packages
        run: echo ${command}
